// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "path";
import { defineConfig } from "prisma/config";

const defaultDatabaseUrl = `file:${path.join(__dirname, "prisma", "dev.db")}`;

export default defineConfig({
  earlyAccess: true,
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? defaultDatabaseUrl,
  },
});
